import categoryRoutes from './category-routes.json';
import personRoutes from './person-routes.json';
import entryRoutes from './entry-routes.json';
import {getCollection} from 'astro:content';
export const sections={cs:{entries:'osobnosti',plants:'rostliny',people:'lide',about:'o-projektu',visit:'navsteva',timeline:'roky',gallery:'galerie',category:'typy'},en:{entries:'people',plants:'plants',people:'participants',about:'about',visit:'visit',timeline:'years',gallery:'gallery',category:'categories'}};
export const text={cs:{people:'Osobnosti',plants:'Stromy a rostliny',about:'Příběh projektu',visit:'Návštěva',joint:'Společný projekt Dariny Miklovičové a Botanické zahrady hl. m. Prahy',search:'Hledat jméno nebo rostlinu…',all:'Všechny profese',years:'Všechny roky',unknown:'Rok nedoložen',sources:'Zdroje',more:'Objevit příběh a výsadbu →',back:'← Zpět na osobnosti',count:'položek',tree:'Stromy',allplants:'Všechny rostliny',participants:'Všichni účastníci',results:'Výsledky'},en:{people:'People',plants:'Trees and plants',about:'About the project',visit:'Visit',joint:'A joint project by Darina Miklovičová and Prague Botanical Garden',search:'Search by name or plant…',all:'All categories',years:'All years',unknown:'Year unconfirmed',sources:'Sources',more:'Discover the story and planting →',back:'← Back to people',count:'entries',tree:'Trees',allplants:'All plants',participants:'All participants',results:'Results'}};
export const homeUrl=lang=>lang==='cs'?'/':'/en/';
export const url=(lang,key,id='')=>key==='category'&&id?`${homeUrl(lang)}${categoryRoutes[id][lang]}/`:`${homeUrl(lang)}${id&&key==='people'?personRoutes[id][lang]:key==='entries'&&id?entryRoutes[id][lang]:sections[lang][key]}/${id?id+'/':''}`;
export async function catalog(){const [entries,articles,plants,people,biographies,categories,pages,plantProfiles]=await Promise.all(['entries','articles','plants','people','biographies','categories','pages','plantProfiles'].map(c=>getCollection(c)));return {entries:entries.sort((a,b)=>a.data.sort_name.localeCompare(b.data.sort_name,'cs')),articles:articles.filter(a=>a.data.status==='ready'),plants,people,biographies,categories,pages,plantProfiles};}
export async function routes(){const c=await catalog();let out=[];for(const lang of ['cs','en']){out.push({path:lang==='cs'?undefined:'en',lang,kind:'home'});for(const key of ['entries','plants','people','about','visit','timeline','gallery'])out.push({path:url(lang,key).slice(1,-1),lang,kind:key});for(const year of [...new Set(c.entries.map(e=>e.data.year).filter(Boolean))])out.push({path:url(lang,'timeline',String(year)).slice(1,-1),lang,kind:'year',id:String(year)});for(const cat of c.categories)out.push({path:url(lang,'category',cat.data.id).slice(1,-1),lang,kind:'category',id:cat.data.id});for(const [collection,key,kind] of [['entries','entries','entry'],['plants','plants','plant'],['people','people','person']])for(const e of c[collection])if(collection!=='people'||!personRoutes[e.data.id].merged)out.push({path:url(lang,key,e.data.id).slice(1,-1),lang,kind,id:e.data.id});}return out;}

const typeLabels={'rodinny-zastupce':'rodinný zástupce','historik-umeni':'historik umění','osobnost-verejneho-zivota':'osobnost veřejného života',lekar:'lékař',hudebnik:'hudebník',sportovec:'sportovec',politik:'politik',herec:'herec',architekt:'architekt',cestovatel:'cestovatel',duchovni:'duchovní',kosmonaut:'kosmonaut',mecenas:'mecenáš',modelka:'modelka',spolek:'spolek',novinar:'novinář',podnikatel:'podnikatel',postava:'pohádková či divadelní postava',reditel:'ředitel kulturní instituce',reziser:'režisér',spisovatel:'spisovatel',tanecnik:'tanečník',veteran:'válečný veterán',vedec:'vědec',vytvarnik:'výtvarník'};
export const personalityType=(entryId,lang)=>lang==='cs'?typeLabels[(entryRoutes[entryId]??personRoutes[entryId])?.cs]:((entryRoutes[entryId]??personRoutes[entryId])?.en??'').replaceAll('-',' ');
