import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';
const collection=(folder,schema)=>defineCollection({loader:glob({pattern:'**/*.md',base:`./content/${folder}`}),schema});
export const collections={
 entries:collection('entries',z.object({id:z.string(),number:z.number(),name:z.string(),sort_name:z.string(),category_id:z.string(),entity_type:z.enum(['person','character','group']),year:z.number().nullable(),date:z.string().nullable(),plant_id:z.string(),planter:z.string(),planter_en:z.string(),person_ids:z.array(z.string()),historical:z.string(),note:z.string(),verified_on:z.string(),planting_id:z.string(),participation:z.string(),sources:z.array(z.object({label_cs:z.string(),label_en:z.string(),url:z.string().url()}))})),
 plantProfiles:collection('plant-profiles',z.object({id:z.string(),plant_id:z.string(),lang:z.enum(['cs','en']),title:z.string(),height:z.string(),flowering:z.string(),longevity:z.string(),source_urls:z.array(z.string().url()),verified_on:z.string(),status:z.string()})),
 articles:collection('articles',z.object({id:z.string(),entry_id:z.string(),lang:z.enum(['cs','en']),title:z.string(),description:z.string(),status:z.enum(['draft','ready']),planting_note:z.string().optional(),biography_source:z.string().url().optional(),text_license:z.string().optional(),text_adaptation:z.string().optional()})),
 plants:collection('plants',z.object({id:z.string(),scientific_name:z.string(),cultivar:z.string(),name_cs:z.string(),name_en:z.string(),plant_type:z.string(),entry_numbers:z.array(z.number()),source_urls:z.array(z.string().url())})),
 people:collection('people',z.object({id:z.string(),name:z.string(),sort_name:z.string(),category_id:z.string(),entry_numbers:z.array(z.number()),source_urls:z.array(z.string().url()),official_website:z.string().url().optional(),biography_verified:z.boolean(),birth_date:z.string().optional(),birth_year:z.number().optional(),birth_place:z.string().optional(),death_date:z.string().optional(),death_year:z.number().optional(),death_place:z.string().optional(),residence:z.string().optional(),highlights_cs:z.array(z.string()).optional(),highlights_en:z.array(z.string()).optional(),facts_source_urls:z.array(z.string().url()).optional(),verified_on:z.string()})),
 biographies:collection('biographies',z.object({id:z.string(),person_id:z.string(),lang:z.enum(['cs','en']),title:z.string(),status:z.string(),source_urls:z.array(z.string().url()),biography_source:z.string().url().optional(),text_license:z.string().optional(),text_adaptation:z.string().optional()})),
 pages:collection('pages',z.object({id:z.string(),lang:z.enum(['cs','en']),page_id:z.string().optional(),hero_title:z.string().optional(),hero_eyebrow:z.string().optional(),hero_intro:z.string().optional(),title:z.string(),status:z.string(),sources:z.array(z.string().url()).optional()})),
 categories:collection('categories',z.object({id:z.string(),name_cs:z.string(),name_en:z.string()}))
};
